import { useState } from 'react';
import { 
  X, 
  Printer, 
  Download, 
  ShieldCheck, 
  FileText, 
  AlertTriangle, 
  Target, 
  CheckCircle, 
  Copy, 
  Check 
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: AnalysisResult;
}

export function ReportModal({ isOpen, onClose, analysis }: ReportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `# SCAMMIRROR INCIDENT ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
Classification: AI-Assisted Social Engineering Threat Assessment

## EXECUTIVE RISK SUMMARY
- **Overall Risk**: ${analysis.overall_risk}
- **Heuristic Risk Score**: ${analysis.risk_score} / 100
- **AI Confidence**: ${analysis.confidence}%
- **Attacker Objective**: ${analysis.attacker_objective}

### Summary
${analysis.summary}

### Targeted Assets
${analysis.targeted_assets.map(a => `- ${a}`).join('\n')}

## DETECTED RED FLAGS
${(analysis.red_flags || []).map(f => `- ${f}`).join('\n')}

## RECONSTRUCTED MANIPULATION STAGES
${analysis.manipulation_stages.map((s, i) => `### Stage ${i + 1}: ${s.stage} (${s.severity})
- **Evidence**: "${s.message_reference || s.evidence}"
- **Psychological Mechanism**: ${s.explanation}
`).join('\n')}

## DEFENSIVE SAFETY RECOMMENDATIONS
${analysis.recommended_actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

---
*Notice: This report was dynamically generated by ScamMirror. Personal identifiable information was sanitized prior to analysis.*
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-[#0B1020]/85 backdrop-blur-md animate-in fade-in duration-200 overflow-y-auto">
      <div 
        id="report-modal-content"
        className="w-full max-w-4xl cyber-card p-6 sm:p-8 shadow-2xl text-[#F8FAFC] my-8 relative"
      >
        {/* Actions Bar */}
        <div className="flex items-center justify-between pb-4 mb-6 border-b border-[#263247]">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-[#00D9FF]/10 border border-[#00D9FF]/30 text-[#00D9FF]">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h2 className="text-lg font-bold text-[#F8FAFC] tracking-tight">
                Safety & Threat Analysis Report
              </h2>
              <p className="text-[11px] font-mono text-[#94A3B8]">
                SCAMMIRROR INCIDENT AUDIT • ID: #{analysis.id?.slice(0, 10) || 'SM-' + Math.random().toString(36).slice(2, 8).toUpperCase()}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 rounded-lg border border-[#263247] bg-[#0B1020] text-xs text-[#CBD5E1] hover:text-white flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[#22C55E]" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="btn-primary-cyber text-xs py-1.5 px-3 flex items-center gap-1.5 shadow-md cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg border border-[#263247] hover:bg-[#111827] text-[#94A3B8] hover:text-white transition-colors cursor-pointer ml-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Document Body */}
        <div className="bg-[#0B1020] border border-[#263247] rounded-xl p-6 sm:p-8 space-y-6 text-sm text-[#CBD5E1] font-sans leading-relaxed">
          {/* Header */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-[#263247]">
            <div>
              <div className="text-xl font-extrabold text-[#F8FAFC] tracking-wider font-mono">
                🪞 SCAM<span className="text-[#00D9FF]">MIRROR</span>
              </div>
              <p className="text-xs text-[#94A3B8] mt-0.5">
                Cybersecurity Social-Engineering Threat Reconstruction
              </p>
            </div>

            <div className="text-left sm:text-right font-mono text-xs text-[#94A3B8]">
              <div>DATE: {new Date().toLocaleDateString()}</div>
              <div>CLASSIFICATION: AI HEURISTIC DEFENSE</div>
            </div>
          </div>

          {/* Risk Level & Score */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 rounded-xl bg-[#151D2E] border border-[#263247]">
            <div>
              <div className="text-[11px] font-mono text-[#94A3B8] uppercase">RISK LEVEL</div>
              <div className="text-lg font-bold text-[#F8FAFC] mt-0.5">{analysis.overall_risk}</div>
            </div>
            <div>
              <div className="text-[11px] font-mono text-[#94A3B8] uppercase">RISK SCORE</div>
              <div className="text-lg font-bold text-[#00D9FF] font-mono mt-0.5">{analysis.risk_score} / 100</div>
            </div>
            <div>
              <div className="text-[11px] font-mono text-[#94A3B8] uppercase">CONFIDENCE</div>
              <div className="text-lg font-bold text-[#22C55E] font-mono mt-0.5">{analysis.confidence}%</div>
            </div>
          </div>

          {/* Conversation Summary */}
          <div className="space-y-1.5">
            <h4 className="text-xs font-mono font-bold text-[#94A3B8] uppercase tracking-wider">
              CONVERSATION SUMMARY
            </h4>
            <p className="text-xs sm:text-sm text-[#CBD5E1] leading-relaxed bg-[#151D2E]/60 p-4 rounded-xl border border-[#263247]">
              {analysis.summary}
            </p>
          </div>

          {/* Probable Objective & Targeted Assets */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-[#151D2E]/60 border border-[#263247] space-y-1">
              <span className="text-[11px] font-mono font-bold text-[#00D9FF] uppercase">
                PROBABLE OBJECTIVE
              </span>
              <p className="text-xs text-[#F8FAFC] font-medium">
                {analysis.attacker_objective}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-[#151D2E]/60 border border-[#263247] space-y-1">
              <span className="text-[11px] font-mono font-bold text-[#00D9FF] uppercase">
                TARGETED ASSETS
              </span>
              <div className="flex flex-wrap gap-1.5 pt-1">
                {analysis.targeted_assets.map((ast, i) => (
                  <span key={i} className="px-2 py-0.5 rounded text-[10px] font-mono bg-[#0B1020] text-[#CBD5E1] border border-[#263247]">
                    {ast}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Detected Red Flags */}
          {analysis.red_flags && analysis.red_flags.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-mono font-bold text-[#EF4444] uppercase tracking-wider">
                DETECTED RED FLAGS
              </h4>
              <div className="flex flex-wrap gap-2">
                {analysis.red_flags.map((flag, idx) => (
                  <span
                    key={idx}
                    className="px-2.5 py-1 rounded text-xs font-mono font-bold bg-[#EF4444]/15 text-[#EF4444] border border-[#EF4444]/30"
                  >
                    🚩 {flag}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Manipulation Stages & Evidence */}
          <div className="space-y-3">
            <h4 className="text-xs font-mono font-bold text-[#94A3B8] uppercase tracking-wider">
              RECONSTRUCTED MANIPULATION STAGES & EVIDENCE
            </h4>
            <div className="space-y-3">
              {analysis.manipulation_stages.map((stage, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-[#151D2E]/60 border border-[#263247] text-xs space-y-1.5">
                  <div className="flex items-center justify-between font-mono font-bold">
                    <span className="text-[#F8FAFC]">
                      Stage {idx + 1}: {stage.stage}
                    </span>
                    <span className="text-[#00D9FF] text-[10px] uppercase">
                      [{stage.severity}]
                    </span>
                  </div>
                  <div className="text-[#CBD5E1] font-mono italic bg-[#0B1020] p-2 rounded border border-[#263247]">
                    "{stage.message_reference || stage.evidence}"
                  </div>
                  <p className="text-[#94A3B8]">
                    {stage.explanation}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Defensive Safety Recommendations */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono font-bold text-[#22C55E] uppercase tracking-wider">
              MANDATORY DEFENSIVE ACTIONS
            </h4>
            <ul className="space-y-1.5 text-xs text-[#CBD5E1]">
              {analysis.recommended_actions.map((act, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-[#22C55E] font-bold shrink-0">{idx + 1}.</span>
                  <span>{act}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Uncertainty Notes */}
          {analysis.uncertainty_notes && analysis.uncertainty_notes.length > 0 && (
            <div className="pt-3 border-t border-[#263247] text-[11px] text-[#64748B] font-mono space-y-1">
              <span className="uppercase text-[#94A3B8] font-semibold">UNCERTAINTY & LIMITATIONS:</span>
              <ul className="list-disc pl-4 space-y-0.5">
                {analysis.uncertainty_notes.map((note, idx) => (
                  <li key={idx}>{note}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
